# __Pandas Fundamentals__

Author: **Rupak Ganvir**

## __Import Libraries__

In [847]:
import pandas as pd
import numpy as np

In [848]:
# Create Data

np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [849]:
# Create DataFrame

df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=["Row1","Row2","Row3","Row4","Row5"], columns=["Col1","Col2","Col3","Col4"])

In [850]:
df.head() # shows the first 5 rows of the dataframe

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [851]:
df.head(3) # shows the first 3 rows of the dataframe

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11

In [852]:
df.tail() # shows the last 5 rows of the dataframe

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [853]:
df.tail(3) # shows the last 3 rows of the dataframe

      Col1  Col2  Col3  Col4
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [854]:
type(df) # shows the type of the dataframe

pandas.core.frame.DataFrame

In [855]:
df.info() # shows the info of the dataframe

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    5 non-null      int64
 1   Col2    5 non-null      int64
 2   Col3    5 non-null      int64
 3   Col4    5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes

In [856]:
df.describe() # shows the statistical summary of the dataframe

            Col1       Col2       Col3       Col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

## Indexing
1) Using column name
2) rowindex[loc]
3) rowindex columnindex number[.iloc]

In [857]:
df.head()

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

### 1) Using Column Name

In [858]:
df["Col1"] # shows the column "Col1" of the dataframe

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Col1, dtype: int64

In [859]:
type(df['Col1']) # shows the type of the column "Col1"

pandas.core.series.Series

In [860]:
df[["Col1","Col2", "Col3"]] # shows the first 5 rows of the dataframe with only the columns Col1, Col2 and Col3. If their are more than 2 clumns then we need to use double square brackets to show the columns. If we use single square brackets then it will show the column as a series. If we use double square brackets then it will show the column as a dataframe.

      Col1  Col2  Col3
Row1     0     1     2
Row2     4     5     6
Row3     8     9    10
Row4    12    13    14
Row5    16    17    18

In [861]:
type(df[["Col1","Col2", "Col3"]]) # shows the type of the dataframe with only the columns Col1, Col2 and Col3. It will show the type as a dataframe because we are using double square brackets to show the columns. If we use single square brackets then it will show the type as a series because it will show the column as a series. If we use double square brackets then it will show the type as a dataframe because it will show the column as a dataframe.

pandas.core.frame.DataFrame

### 2) Using Row Index Name (loc)

In [862]:
df.loc["Row3"] # shows the row "Row3" of the dataframe

Col1     8
Col2     9
Col3    10
Col4    11
Name: Row3, dtype: int64

In [863]:
type(df.loc["Row3"]) # shows the type of the row "Row3" of the dataframe. It will show the type as a series because it will show the row as a series. If we use double square brackets then it will show the type as a dataframe because it will show the row as a dataframe.

pandas.core.series.Series

In [864]:
df.loc[["Row1","Row2","Row4"]] # shows the rows "Row1", "Row2" and "Row4" of the dataframe. If their are more than 2 rows then we need to use double square brackets to show the rows. If we use single square brackets then it will show the row as a series. If we use double square brackets then it will show the row as a dataframe.

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row4    12    13    14    15

In [865]:
type(df.loc[["Row1","Row2","Row4"]]) # shows the type of the dataframe with only the rows "Row1", "Row2" and "Row4". It will show the type as a dataframe because we are using double square brackets to show the rows. If we use single square brackets then it will show the type as a series because it will show the row as a series. If we use double square brackets then it will show the type as a dataframe because it will show the row as a dataframe.

pandas.core.frame.DataFrame

### Using Row Cloumn Index Number (iloc)

In [866]:
df.iloc[2:4,0:2] # shows the rows from index 2 to 4 and columns from index 0 to 2 of the dataframe. It will show the rows "Row3" and "Row4" and columns "Col1" and "Col2" of the dataframe. If we use single square brackets then it will show the row as a series. If we use double square brackets then it will show the row as a dataframe.

      Col1  Col2
Row3     8     9
Row4    12    13

In [867]:
df.iloc[3:,3:] # shows the rows from index 3 to the end and columns from index 3 to the end of the dataframe. It will show the rows "Row4" and "Row5" and column "Col4" of the dataframe. If we use single square brackets then it will show the row as a series. If we use double square brackets then it will show the row as a dataframe.

      Col4
Row4    15
Row5    19

In [868]:
# Exercise 1: Show the columns "Col1" and "Col4" of the dataframe using iloc.

#Solution 1:
df[["Col1","Col4"]].iloc[:,0:3] # shows the columns "Col1" and "Col4" of the dataframe using iloc. It will show the columns "Col1" and "Col4" of the dataframe.

      Col1  Col4
Row1     0     3
Row2     4     7
Row3     8    11
Row4    12    15
Row5    16    19

### Convert DataFrames into Arrays

In [869]:
df.iloc[:,1:].values # shows the values of the dataframe with only the columns from index 1 to the end. It will show the values of the dataframe with only the columns "Col2", "Col3" and "Col4".

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

### Basic Operations

In [870]:
# Null value or not

df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [871]:
# Creating a new dataframe with null values

df1 = pd.DataFrame(data=[[1, np.nan, 2], [np.nan, 2, 6]], index=["Row1","Row2"], columns=["Col1","Col2","Col3"]) # np.nan is used to create a null value
df1.head()

      Col1  Col2  Col3
Row1   1.0   NaN     2
Row2   NaN   2.0     6

In [872]:
df1.isnull().sum()

Col1    1
Col2    1
Col3    0
dtype: int64

In [873]:
df1.isnull().sum()==0

Col1    False
Col2    False
Col3     True
dtype: bool

In [874]:
# Count of each value in the column

df1["Col3"].value_counts() # shows the count of the values in the column "Col3" of the dataframe. It will show the count of the value 2 and 6 in the column "Col3" of the dataframe. It will show the count as 1 for both values because there is only one occurrence of each value in the column "Col3" of the dataframe.

Col3
2    1
6    1
Name: count, dtype: int64

In [875]:
# How many unique values

df1["Col2"].unique()

array([nan,  2.])

In [876]:
print(df>2)
print("\n")
print(df["Col2"]>2)

       Col1   Col2   Col3  Col4
Row1  False  False  False  True
Row2   True   True   True  True
Row3   True   True   True  True
Row4   True   True   True  True
Row5   True   True   True  True


Row1    False
Row2     True
Row3     True
Row4     True
Row5     True
Name: Col2, dtype: bool

In [877]:
# Show all the values which are greater than 2, others NaN

df[df>2]

      Col1  Col2  Col3  Col4
Row1   NaN   NaN   NaN     3
Row2   4.0   5.0   6.0     7
Row3   8.0   9.0  10.0    11
Row4  12.0  13.0  14.0    15
Row5  16.0  17.0  18.0    19

In [878]:
# Show the specific rows where the column "Col2" is greater than 5

df[df["Col2"]>5]

      Col1  Col2  Col3  Col4
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

## Reading Different Data Sources With The Help Of Pandas

In [879]:
from io import StringIO

In [880]:
df2 = pd.read_csv('Data/Data.csv') #read csv file and create a dataframe df2
df2.head() # show the first 5 rows of the dataframe

  Station            N           E        Z    ID
0    gcp5  2933168.095  423424.892  127.940    CP
1   gcp11  2933154.401  423512.530  128.118    CP
2       1  2933161.058  423429.481  127.734    SL
3       2  2933153.699  423419.607  127.066  TREE
4       3  2933140.440  423421.144  127.005  TREE

In [881]:
type(df2)

pandas.core.frame.DataFrame

In [882]:
# Create the data

data1 = ('col1,col2,col3,col4\n'
         '1,4,3,8\n'
         '1,3,5,7\n'
         '2,5,4,9')

In [883]:
type(data1)

str

In [884]:
# In memory file format object

StringIO(data1)

In [885]:
pd.read_csv(StringIO(data1))

   col1  col2  col3  col4
0     1     4     3     8
1     1     3     5     7
2     2     5     4     9

In [886]:
# If we want to show only perticular columns from our data

df3 = pd.read_csv(StringIO(data1),usecols=['col1','col2'])

In [887]:
# Save this newly genwrated data in csv

df3.to_csv('Output/new_file.csv', index=False) # by default index is true which means in saved file containd index(0,1,2,...) for each row, if we make it false then it won't show those index in the file

## Datatypes in csv

In [888]:
data2 = ('col1,col2,col3,col4\n'
         'a,4,3,8\n'
         'b,3,5,7\n'
         'a,1,4')
df4 = pd.read_csv(StringIO(data2)) 
df4 # While creating a dataset if some value is missing then it takes NaN by default

  col1  col2  col3  col4
0    a     4     3   8.0
1    b     3     5   7.0
2    a     1     4   NaN

In [889]:
# Info about the dataframe

df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      object
 1   col2    3 non-null      int64
 2   col3    3 non-null      int64
 3   col4    2 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 228.0+ bytes

In [890]:
# To change the datatype of the data

df4 = pd.read_csv(StringIO(data2), dtype='object') # in place of object we can write float, int32, etc to change the data type
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      object
 1   col2    3 non-null      object
 2   col3    3 non-null      object
 3   col4    2 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes

In [891]:
df4 = pd.read_csv(StringIO(data2), dtype={'col1':object,'col2':float,'col3':int})
print(df4.info(),"\n")
print(df4.dtypes) # Different way to show the datatype of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      object
 1   col2    3 non-null      float64
 2   col3    3 non-null      int64
 3   col4    2 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 228.0+ bytes
None

col1     object
col2    float64
col3      int64
col4    float64
dtype: object

In [892]:
df4.head()

  col1  col2  col3  col4
0    a   4.0     3   8.0
1    b   3.0     5   7.0
2    a   1.0     4   NaN

In [893]:
# If we want a perticular value from the dataframe

print(df4['col1'], "\n") # gives whole column
print(df4['col2'][1]) # Gives the value at index 1 of col2

0    a
1    b
2    a
Name: col1, dtype: object

3.0

In [894]:
pd.read_csv(StringIO(data2), index_col=0) # index_col=0 uses column 0 (the first column) as the DataFrame index

      col2  col3  col4
col1
a        4     3   8.0
b        3     5   7.0
a        1     4   NaN

In [895]:
# Use index_col and usecols

pd.read_csv(StringIO(data2),usecols=['col1','col2'], index_col=1)

     col1
col2
4       a
3       b
1       a

In [896]:
df6 = pd.read_csv('Data/TabSeparatedData.csv',sep=r'\s+')   # One or more whitespace characters (spaces, tabs, etc.) are separated
df6

     Name  RollNo.  RoomNo.
0   Rupak    12345      123
1  Avirup    67890      345
2  Tushar    34567      567

## Adding / Dropping Columns and Rows

In real data pipelines you often need to create new columns from existing ones, or remove columns and rows that are not needed.

In [897]:
# Re-create our base dataframe

df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=["Row1","Row2","Row3","Row4","Row5"], columns=["Col1","Col2","Col3","Col4"])
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [898]:
# Adding a new column

df["Col5"] = df["Col1"] + df["Col2"] # New column = sum of Col1 and Col2
df

      Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     1
Row2     4     5     6     7     9
Row3     8     9    10    11    17
Row4    12    13    14    15    25
Row5    16    17    18    19    33

In [899]:
# Adding a new column with a constant value

df["Col6"] = 100 # Every row in Col6 will have value 100
df

      Col1  Col2  Col3  Col4  Col5  Col6
Row1     0     1     2     3     1   100
Row2     4     5     6     7     9   100
Row3     8     9    10    11    17   100
Row4    12    13    14    15    25   100
Row5    16    17    18    19    33   100

In [900]:
# Dropping a column

df = df.drop("Col6", axis=1) # axis=1 means we are dropping a column. If axis=0 it means we are dropping a row.
df

      Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     1
Row2     4     5     6     7     9
Row3     8     9    10    11    17
Row4    12    13    14    15    25
Row5    16    17    18    19    33

In [901]:
# Dropping multiple columns at once

df = df.drop(["Col5"], axis=1)
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [902]:
# Dropping a row

df_dropped = df.drop("Row3", axis=0) # axis=0 means we are dropping a row
df_dropped

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row4    12    13    14    15
Row5    16    17    18    19

In [903]:
# Dropping multiple rows at once

df_dropped = df.drop(["Row1", "Row5"], axis=0)
df_dropped

      Col1  Col2  Col3  Col4
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15

In [904]:
# Note: drop() does not change the original dataframe unless we use inplace=True

print(df) # Original df is unchanged because we stored result in df_dropped

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

## Sorting

sort_values() sorts the dataframe by the values in one or more columns. sort_index() sorts by the index labels.

In [905]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, 22, 35, 28],
    "Salary": [50000, 70000, 45000, 90000, 60000]
})

df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   70000
2  Charlie   22   45000
3    David   35   90000
4      Eve   28   60000

In [906]:
# Sort by a single column (ascending by default)

df.sort_values("Age") # Sort by Age in ascending order

      Name  Age  Salary
2  Charlie   22   45000
0    Alice   25   50000
4      Eve   28   60000
1      Bob   30   70000
3    David   35   90000

In [907]:
# Sort in descending order

df.sort_values("Salary", ascending=False) # Sort by Salary from highest to lowest

      Name  Age  Salary
3    David   35   90000
1      Bob   30   70000
4      Eve   28   60000
0    Alice   25   50000
2  Charlie   22   45000

In [908]:
# Sort by multiple columns

df.sort_values(["Age", "Salary"]) # Sort by Age first, then by Salary for ties

      Name  Age  Salary
2  Charlie   22   45000
0    Alice   25   50000
4      Eve   28   60000
1      Bob   30   70000
3    David   35   90000

In [909]:
# Sort by index

df_rev = df.sort_index(ascending=False) # Reverse the index order
df_rev

      Name  Age  Salary
4      Eve   28   60000
3    David   35   90000
2  Charlie   22   45000
1      Bob   30   70000
0    Alice   25   50000

## Missing Data Handling

Real-world datasets almost always have missing values. Pandas represents missing values as NaN (Not a Number). We already saw isnull() and isnull().sum() to detect them. Now we learn how to handle them properly.

In [910]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, np.nan, 22, 35, np.nan],
    "Salary": [50000, 70000, np.nan, 90000, 60000],
    "City": ["Delhi", "Mumbai", np.nan, "Pune", "Delhi"]
})

df

      Name   Age   Salary    City
0    Alice  25.0  50000.0   Delhi
1      Bob   NaN  70000.0  Mumbai
2  Charlie  22.0      NaN     NaN
3    David  35.0  90000.0    Pune
4      Eve   NaN  60000.0   Delhi

In [911]:
# Check how many NaN values are in each column

df.isnull().sum()

Name      0
Age       2
Salary    1
City      1
dtype: int64

In [912]:
# dropna() → removes rows that have any NaN value

df.dropna() # Drops every row where at least one value is NaN

    Name   Age   Salary   City
0  Alice  25.0  50000.0  Delhi
3  David  35.0  90000.0   Pune

In [913]:
# dropna() with how parameter

df.dropna(how='all') # Only drop a row if ALL values in that row are NaN (nothing dropped here since no row is all NaN)

      Name   Age   Salary    City
0    Alice  25.0  50000.0   Delhi
1      Bob   NaN  70000.0  Mumbai
2  Charlie  22.0      NaN     NaN
3    David  35.0  90000.0    Pune
4      Eve   NaN  60000.0   Delhi

In [914]:
# dropna() along axis=1 drops columns that have any NaN

df.dropna(axis=1) # Drops every column that has at least one NaN

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eve

In [915]:
# dropna() with thresh parameter

df.dropna(thresh=3) # Keep only rows that have at least 3 non-NaN values

    Name   Age   Salary    City
0  Alice  25.0  50000.0   Delhi
1    Bob   NaN  70000.0  Mumbai
3  David  35.0  90000.0    Pune
4    Eve   NaN  60000.0   Delhi

In [916]:
# fillna() → fills NaN values with a specific value

df.fillna(0) # Replace all NaN with 0

      Name   Age   Salary    City
0    Alice  25.0  50000.0   Delhi
1      Bob   0.0  70000.0  Mumbai
2  Charlie  22.0      0.0       0
3    David  35.0  90000.0    Pune
4      Eve   0.0  60000.0   Delhi

In [917]:
# Fill each column with a different value

df.fillna({"Age": df["Age"].mean(), "Salary": df["Salary"].median(), "City": "Unknown"}) # Fill Age with mean, Salary with median, City with 'Unknown'

      Name        Age   Salary     City
0    Alice  25.000000  50000.0    Delhi
1      Bob  27.333333  70000.0   Mumbai
2  Charlie  22.000000  65000.0  Unknown
3    David  35.000000  90000.0     Pune
4      Eve  27.333333  60000.0    Delhi

In [918]:
# Forward fill (ffill) → fills NaN with the value from the previous row

df.ffill() # Each NaN gets the value from the row above it

      Name   Age   Salary    City
0    Alice  25.0  50000.0   Delhi
1      Bob  25.0  70000.0  Mumbai
2  Charlie  22.0  70000.0  Mumbai
3    David  35.0  90000.0    Pune
4      Eve  35.0  60000.0   Delhi

In [919]:
# Backward fill (bfill) → fills NaN with the value from the next row

df.bfill() # Each NaN gets the value from the row below it

      Name   Age   Salary    City
0    Alice  25.0  50000.0   Delhi
1      Bob  22.0  70000.0  Mumbai
2  Charlie  22.0  90000.0    Pune
3    David  35.0  90000.0    Pune
4      Eve   NaN  60000.0   Delhi

In [920]:
# interpolate() → fills NaN by interpolating between surrounding values

# This is very useful for time-series data like sensor readings or satellite data

df_ts = pd.DataFrame({
    "Displacement": [1.0, np.nan, 3.0, np.nan, 5.0] # Suppose these are InSAR displacement values
})

print(df_ts)
print(df_ts.interpolate()) # Linearly interpolates between 1.0 and 3.0 to fill the gap

   Displacement
0           1.0
1           NaN
2           3.0
3           NaN
4           5.0
   Displacement
0           1.0
1           2.0
2           3.0
3           4.0
4           5.0

## Data Type Conversion

We already saw how to set dtypes while reading a CSV. But often we need to convert column types after loading the data.

In [921]:
df = pd.DataFrame({
    "ID": ["1", "2", "3", "4"],    # Stored as string
    "Score": ["85.5", "90.0", "abc", "78.3"], # Has a bad value 'abc'
    "Passed": [1, 0, 1, 1]           # Stored as int, but should be bool
})

print(df.dtypes)
df

ID        object
Score     object
Passed     int64
dtype: object

  ID Score  Passed
0  1  85.5       1
1  2  90.0       0
2  3   abc       1
3  4  78.3       1

In [922]:
# astype() → convert column to a specific type

df["ID"] = df["ID"].astype(int) # Convert ID from string to int
df["Passed"] = df["Passed"].astype(bool) # Convert Passed from int to bool

print(df.dtypes)
df

ID         int64
Score     object
Passed      bool
dtype: object

   ID Score  Passed
0   1  85.5    True
1   2  90.0   False
2   3   abc    True
3   4  78.3    True

In [923]:
# pd.to_numeric() → convert column to numeric, with error handling

# astype() would raise an error on 'abc'. pd.to_numeric() with errors='coerce' converts bad values to NaN instead of crashing

df["Score"] = pd.to_numeric(df["Score"], errors='coerce') # 'abc' becomes NaN
print(df.dtypes)
df

ID          int64
Score     float64
Passed       bool
dtype: object

   ID  Score  Passed
0   1   85.5    True
1   2   90.0   False
2   3    NaN    True
3   4   78.3    True

## apply(), map() and transform()

These are the most important functions for applying custom operations to rows or columns. Instead of writing loops, you pass a function to these methods and Pandas applies it efficiently.

In [924]:
df = pd.DataFrame({
    "Name": ["alice", "BOB", "Charlie", "david"],
    "Score": [85, 92, 78, 95],
    "Salary": [50000, 70000, 45000, 90000]
})

df

      Name  Score  Salary
0    alice     85   50000
1      BOB     92   70000
2  Charlie     78   45000
3    david     95   90000

In [925]:
# apply() on a column → applies a function to each element in the column

df["Name"] = df["Name"].apply(str.title) # Convert each name to title case
df

      Name  Score  Salary
0    Alice     85   50000
1      Bob     92   70000
2  Charlie     78   45000
3    David     95   90000

In [926]:
# apply() with a custom function (lambda)

df["Grade"] = df["Score"].apply(lambda x: "Pass" if x >= 80 else "Fail") # Create a new column based on a condition
df

      Name  Score  Salary Grade
0    Alice     85   50000  Pass
1      Bob     92   70000  Pass
2  Charlie     78   45000  Fail
3    David     95   90000  Pass

In [927]:
# apply() on a full dataframe (axis=1 means apply row-wise)

# Suppose we want to create a new column that combines Name and Grade as a label
df["Label"] = df.apply(lambda row: row["Name"] + " - " + row["Grade"], axis=1) # axis=1 → process each row
df

      Name  Score  Salary Grade           Label
0    Alice     85   50000  Pass    Alice - Pass
1      Bob     92   70000  Pass      Bob - Pass
2  Charlie     78   45000  Fail  Charlie - Fail
3    David     95   90000  Pass    David - Pass

In [928]:
# apply() with axis=0 → apply function column-wise

print(df[["Score", "Salary"]].apply(lambda col: col.max() - col.min(), axis=0)) # Range (max - min) for each column

Score        17
Salary    45000
dtype: int64

In [929]:
# map() → applies a function or a dictionary mapping to a Series

# Useful for mapping categorical values to numbers (label encoding)

grade_map = {"Pass": 1, "Fail": 0} # Dictionary mapping
df["Grade_Numeric"] = df["Grade"].map(grade_map) # Map Grade column using the dictionary
df

      Name  Score  Salary Grade           Label  Grade_Numeric
0    Alice     85   50000  Pass    Alice - Pass              1
1      Bob     92   70000  Pass      Bob - Pass              1
2  Charlie     78   45000  Fail  Charlie - Fail              0
3    David     95   90000  Pass    David - Pass              1

In [930]:
# transform() → applies a function but keeps the original shape (same index as original)

# Useful when you want to compute group-level stats but keep them aligned with the original dataframe

df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Sales", "HR", "Sales"],
    "Salary": [70000, 50000, 80000, 60000, 55000, 65000]
})

# Add a column showing the average salary of each person's department (not just a summary — it stays aligned)
df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")
df

  Department  Salary  Dept_Avg_Salary
0         IT   70000          75000.0
1         HR   50000          52500.0
2         IT   80000          75000.0
3      Sales   60000          62500.0
4         HR   55000          52500.0
5      Sales   65000          62500.0

## Merging and Joining DataFrames

In real projects you rarely have all the data in one table. pd.merge() lets you combine two DataFrames based on a common column, similar to SQL joins. pd.concat() stacks DataFrames on top of each other or side by side.

In [931]:
# Create two dataframes to merge

df_employees = pd.DataFrame({
    "EmpID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "DeptID": [10, 20, 10, 30]
})

df_departments = pd.DataFrame({
    "DeptID": [10, 20, 30, 40],
    "DeptName": ["IT", "HR", "Sales", "Finance"]
})

print(df_employees)
print(df_departments)

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      10
3      4    David      30
   DeptID DeptName
0      10       IT
1      20       HR
2      30    Sales
3      40  Finance

In [932]:
# Inner Join → Only keeps rows that have matching DeptID in BOTH dataframes

pd.merge(df_employees, df_departments, on="DeptID", how="inner") # DeptID=40 disappears because no employee belongs to Finance

   EmpID     Name  DeptID DeptName
0      1    Alice      10       IT
1      2      Bob      20       HR
2      3  Charlie      10       IT
3      4    David      30    Sales

In [933]:
# Left Join → Keeps all rows from the left dataframe, fills NaN where no match in right

pd.merge(df_employees, df_departments, on="DeptID", how="left") # All employees are kept

   EmpID     Name  DeptID DeptName
0      1    Alice      10       IT
1      2      Bob      20       HR
2      3  Charlie      10       IT
3      4    David      30    Sales

In [934]:
# Right Join → Keeps all rows from the right dataframe, fills NaN where no match in left

pd.merge(df_employees, df_departments, on="DeptID", how="right") # Finance department appears with NaN for employee info

   EmpID     Name  DeptID DeptName
0    1.0    Alice      10       IT
1    3.0  Charlie      10       IT
2    2.0      Bob      20       HR
3    4.0    David      30    Sales
4    NaN      NaN      40  Finance

In [935]:
# Outer Join → Keeps all rows from both dataframes, fills NaN where no match

pd.merge(df_employees, df_departments, on="DeptID", how="outer")

   EmpID     Name  DeptID DeptName
0    1.0    Alice      10       IT
1    3.0  Charlie      10       IT
2    2.0      Bob      20       HR
3    4.0    David      30    Sales
4    NaN      NaN      40  Finance

In [936]:
# pd.concat() → stacks DataFrames vertically (on top of each other)

df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "Score": [85, 90]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "Score": [78, 95]})

pd.concat([df1, df2]) # Stack df2 below df1

      Name  Score
0    Alice     85
1      Bob     90
0  Charlie     78
1    David     95

In [937]:
# pd.concat() with ignore_index=True to reset the index

pd.concat([df1, df2], ignore_index=True) # Reset index to 0,1,2,3 instead of 0,1,0,1

      Name  Score
0    Alice     85
1      Bob     90
2  Charlie     78
3    David     95

In [938]:
# pd.concat() horizontally (axis=1) → adds columns side by side

df_names = pd.DataFrame({"Name": ["Alice", "Bob", "Charlie"]})
df_scores = pd.DataFrame({"Score": [85, 90, 78]})

pd.concat([df_names, df_scores], axis=1) # Place columns side by side

      Name  Score
0    Alice     85
1      Bob     90
2  Charlie     78

## GroupBy

In [939]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Sales", "HR", "Sales"],
    "Salary": [70000, 50000, 80000, 60000, 55000, 65000]
})

df

  Department  Salary
0         IT   70000
1         HR   50000
2         IT   80000
3      Sales   60000
4         HR   55000
5      Sales   65000

In [940]:
# Suppose the question is what is the avg salary in each department?

df.groupby("Department")["Salary"].mean()  # Pandas internally creates groups -> Apply mean -> Combine

Department
HR       52500.0
IT       75000.0
Sales    62500.0
Name: Salary, dtype: float64

In [941]:
# Count (Suppose we want how many employees in each department)

df.groupby("Department").count()

            Salary
Department
HR               2
IT               2
Sales            2

In [942]:
# Sum of all employee salaries department wise

df.groupby("Department").sum()

            Salary
Department
HR          105000
IT          150000
Sales       125000

In [943]:
# Maximum salary in each department

df.groupby("Department").max()

            Salary
Department
HR           55000
IT           80000
Sales        65000

In [944]:
# We can combine all those operations and get it in one

df.groupby("Department")["Salary"].agg(
    ["mean", "sum", "min", "max", "count"]
)

               mean     sum    min    max  count
Department
HR          52500.0  105000  50000  55000      2
IT          75000.0  150000  70000  80000      2
Sales       62500.0  125000  60000  65000      2

In [945]:
# GroupBy with multiple columns

df = pd.DataFrame({
    "Department": ["IT","HR","IT","Sales","HR","Sales"],
    "Salary": [70000,50000,80000,60000,55000,65000],
    "Age": [25,30,28,35,29,40]
})

print(df)

df.groupby("Department")[["Salary", "Age"]].agg(['mean', 'min', 'max', 'sum'])

  Department  Salary  Age
0         IT   70000   25
1         HR   50000   30
2         IT   80000   28
3      Sales   60000   35
4         HR   55000   29
5      Sales   65000   40

             Salary                         Age
               mean    min    max     sum  mean min max sum
Department
HR          52500.0  50000  55000  105000  29.5  29  30  59
IT          75000.0  70000  80000  150000  26.5  25  28  53
Sales       62500.0  60000  65000  125000  37.5  35  40  75

## Aggregation

Aggregation functions reduce a column or group of values down to a single number. We already used agg() inside GroupBy. Here we look at aggregation on the full dataframe and custom aggregation functions.

In [946]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Sales", "HR", "Sales"],
    "Salary": [70000, 50000, 80000, 60000, 55000, 65000],
    "Age": [25, 30, 28, 35, 29, 40]
})

df

  Department  Salary  Age
0         IT   70000   25
1         HR   50000   30
2         IT   80000   28
3      Sales   60000   35
4         HR   55000   29
5      Sales   65000   40

In [947]:
# Applying aggregation on the whole dataframe (on numeric columns)

df[["Salary", "Age"]].agg(["mean", "min", "max", "sum", "count"])

              Salary         Age
mean    63333.333333   31.166667
min     50000.000000   25.000000
max     80000.000000   40.000000
sum    380000.000000  187.000000
count       6.000000    6.000000

In [948]:
# Different aggregations for different columns using a dictionary

df.agg({"Salary": ["mean", "max"], "Age": ["min", "median"]})

              Salary   Age
mean    63333.333333   NaN
max     80000.000000   NaN
min              NaN  25.0
median           NaN  29.5

In [949]:
# Custom aggregation function with agg()

# Suppose we want the range (max - min) for each column
def range_func(x):
    return x.max() - x.min()

df[["Salary", "Age"]].agg(range_func)

Salary    30000
Age          15
dtype: int64

In [950]:
# Named aggregation with groupby → gives clean column names to aggregated results

df.groupby("Department").agg(
    Avg_Salary=("Salary", "mean"),  # Name the result column 'Avg_Salary'
    Max_Age=("Age", "max"),         # Name the result column 'Max_Age'
    Headcount=("Salary", "count")   # Name the result column 'Headcount'
)

            Avg_Salary  Max_Age  Headcount
Department
HR             52500.0       30          2
IT             75000.0       28          2
Sales          62500.0       40          2

## String Operations (str accessor)

Pandas provides a str accessor to apply string operations to every element in a Series at once. This is much faster than looping and handles NaN values automatically.

In [951]:
df = pd.DataFrame({
    "Name": ["alice smith", "BOB JONES", "Charlie Brown", "david lee", np.nan],
    "Email": ["alice@gmail.com", "bob@yahoo.com", "charlie@gmail.com", "david@outlook.com", "eve@gmail.com"],
    "City": ["  New Delhi  ", "Mumbai", "Bangalore", "  Pune ", "Chennai"]
})

df

            Name              Email           City
0    alice smith    alice@gmail.com    New Delhi
1      BOB JONES      bob@yahoo.com         Mumbai
2  Charlie Brown  charlie@gmail.com      Bangalore
3      david lee  david@outlook.com          Pune
4            NaN      eve@gmail.com        Chennai

In [952]:
# Convert to lowercase, uppercase, and title case

print(df["Name"].str.lower())  # All lowercase
print(df["Name"].str.upper())  # All uppercase
print(df["Name"].str.title())  # Title Case (NaN is kept as NaN automatically)

0      alice smith
1        bob jones
2    charlie brown
3        david lee
4              NaN
Name: Name, dtype: object
0      ALICE SMITH
1        BOB JONES
2    CHARLIE BROWN
3        DAVID LEE
4              NaN
Name: Name, dtype: object
0      Alice Smith
1        Bob Jones
2    Charlie Brown
3        David Lee
4              NaN
Name: Name, dtype: object

In [953]:
# Strip whitespace from both ends of each string

print(df["City"].str.strip()) # Removes leading and trailing spaces from 'New Delhi' and 'Pune'

0    New Delhi
1       Mumbai
2    Bangalore
3         Pune
4      Chennai
Name: City, dtype: object

In [954]:
# Check if a string contains a pattern

print(df["Email"].str.contains("gmail")) # Returns True where Email contains 'gmail'

0     True
1    False
2     True
3    False
4     True
Name: Email, dtype: bool

In [955]:
# Filter rows where Email contains 'gmail'

df[df["Email"].str.contains("gmail")]

            Name              Email           City
0    alice smith    alice@gmail.com    New Delhi
2  Charlie Brown  charlie@gmail.com      Bangalore
4            NaN      eve@gmail.com        Chennai

In [956]:
# Split a string column into multiple parts

# Split the Name column at the space to separate first and last name
split_names = df["Name"].str.split(" ", expand=True) # expand=True returns a DataFrame instead of a Series of lists
split_names.columns = ["First Name", "Last Name"]
split_names

  First Name Last Name
0      alice     smith
1        BOB     JONES
2    Charlie     Brown
3      david       lee
4        NaN       NaN

In [957]:
# Replace part of a string

df["Email"].str.replace("gmail.com", "company.com") # Replace gmail.com with company.com in all emails

0      alice@company.com
1          bob@yahoo.com
2    charlie@company.com
3      david@outlook.com
4        eve@company.com
Name: Email, dtype: object

In [958]:
# Get the length of each string

df["Name"].str.len() # Returns the number of characters in each name

0    11.0
1     9.0
2    13.0
3     9.0
4     NaN
Name: Name, dtype: float64

## DateTime Handling

Time-series data is very common in geospatial work — sensor readings, satellite acquisition dates, climate data like ERA5. Pandas has excellent support for working with dates and times through the dt accessor and pd.to_datetime().

In [959]:
df = pd.DataFrame({
    "Date": ["2024-01-15", "2024-03-22", "2024-06-10", "2024-09-05", "2024-12-31"],
    "Displacement": [1.2, 2.5, 3.1, 4.8, 5.3] # Suppose these are InSAR displacement values in mm
})

print(df.dtypes) # Date is stored as object (string) right now
df

Date             object
Displacement    float64
dtype: object

         Date  Displacement
0  2024-01-15           1.2
1  2024-03-22           2.5
2  2024-06-10           3.1
3  2024-09-05           4.8
4  2024-12-31           5.3

In [960]:
# pd.to_datetime() → converts a string column to datetime type

df["Date"] = pd.to_datetime(df["Date"])
print(df.dtypes) # Date is now datetime64
df

Date            datetime64[ns]
Displacement           float64
dtype: object

        Date  Displacement
0 2024-01-15           1.2
1 2024-03-22           2.5
2 2024-06-10           3.1
3 2024-09-05           4.8
4 2024-12-31           5.3

In [961]:
# Once converted to datetime, we can use the dt accessor to extract date parts

print(df["Date"].dt.year)   # Extract year
print(df["Date"].dt.month)  # Extract month
print(df["Date"].dt.day)    # Extract day
print(df["Date"].dt.day_name()) # Get the day of the week

0    2024
1    2024
2    2024
3    2024
4    2024
Name: Date, dtype: int32
0     1
1     3
2     6
3     9
4    12
Name: Date, dtype: int32
0    15
1    22
2    10
3     5
4    31
Name: Date, dtype: int32
0      Monday
1      Friday
2      Monday
3    Thursday
4     Tuesday
Name: Date, dtype: object

In [962]:
# Set Date as the index (very useful for time-series)

df = df.set_index("Date")
df

            Displacement
Date
2024-01-15           1.2
2024-03-22           2.5
2024-06-10           3.1
2024-09-05           4.8
2024-12-31           5.3

In [963]:
# Resample → aggregate data at a different time frequency

# Suppose we have daily data and want to compute monthly average displacement

df_daily = pd.DataFrame({
    "Displacement": [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5]
}, index=pd.date_range(start="2024-01-01", periods=12, freq="ME")) # ME = Month End frequency

print(df_daily)

# Resample to quarterly and compute mean
df_daily.resample("QE").mean() # QE = Quarter End

            Displacement
2024-01-31           1.0
2024-02-29           1.5
2024-03-31           2.0
2024-04-30           2.5
2024-05-31           3.0
2024-06-30           3.5
2024-07-31           4.0
2024-08-31           4.5
2024-09-30           5.0
2024-10-31           5.5
2024-11-30           6.0
2024-12-31           6.5

            Displacement
2024-03-31           1.5
2024-06-30           3.0
2024-09-30           4.5
2024-12-31           6.0

In [964]:
# Rolling window → compute moving average over a sliding window

# A rolling mean smooths out noise in time-series data

df_daily["Rolling_Mean_3"] = df_daily["Displacement"].rolling(window=3).mean() # 3-period moving average
df_daily

            Displacement  Rolling_Mean_3
2024-01-31           1.0             NaN
2024-02-29           1.5             NaN
2024-03-31           2.0             1.5
2024-04-30           2.5             2.0
2024-05-31           3.0             2.5
2024-06-30           3.5             3.0
2024-07-31           4.0             3.5
2024-08-31           4.5             4.0
2024-09-30           5.0             4.5
2024-10-31           5.5             5.0
2024-11-30           6.0             5.5
2024-12-31           6.5             6.0

## Window Functions

Window functions compute values over a sliding or expanding window. They are especially useful for time-series analysis — smoothing, trend detection, and cumulative statistics.

In [965]:
df = pd.DataFrame({
    "Month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    "Sales": [100, 120, 90, 150, 130, 170]
})

df

  Month  Sales
0   Jan    100
1   Feb    120
2   Mar     90
3   Apr    150
4   May    130
5   Jun    170

In [966]:
# rolling() → moving window

df["Rolling_Mean_3"] = df["Sales"].rolling(window=3).mean() # Average of the current and 2 previous values
df["Rolling_Max_3"] = df["Sales"].rolling(window=3).max()   # Max in each window of 3
df

  Month  Sales  Rolling_Mean_3  Rolling_Max_3
0   Jan    100             NaN            NaN
1   Feb    120             NaN            NaN
2   Mar     90      103.333333          120.0
3   Apr    150      120.000000          150.0
4   May    130      123.333333          150.0
5   Jun    170      150.000000          170.0

In [967]:
# expanding() → growing window (uses all data from the start up to the current row)

df["Expanding_Mean"] = df["Sales"].expanding().mean() # Average of all values up to and including the current row
df["Expanding_Sum"] = df["Sales"].expanding().sum()   # Cumulative sum up to current row
df

  Month  Sales  Rolling_Mean_3  Rolling_Max_3  Expanding_Mean  Expanding_Sum
0   Jan    100             NaN            NaN      100.000000          100.0
1   Feb    120             NaN            NaN      110.000000          220.0
2   Mar     90      103.333333          120.0      103.333333          310.0
3   Apr    150      120.000000          150.0      115.000000          460.0
4   May    130      123.333333          150.0      118.000000          590.0
5   Jun    170      150.000000          170.0      126.666667          760.0

In [968]:
# ewm() → Exponentially Weighted Mean (gives more weight to recent values)

# span controls how quickly the weights decay. Lower span = more weight on recent values.
df["EWM_Mean"] = df["Sales"].ewm(span=3).mean()
df

,Month,Sales,Rolling_Mean_3,Rolling_Max_3,Expanding_Mean,Expanding_Sum,EWM_Mean
0,Jan,100,NaN,NaN,100.000000,100.0,100.000000
1,Feb,120,NaN,NaN,110.000000,220.0,113.333333
2,Mar,90,103.333333,120.0,103.333333,310.0,100.000000
3,Apr,150,120.000000,150.0,115.000000,460.0,126.666667
4,May,130,123.333333,150.0,118.000000,590.0,128.387097
5,Jun,170,150.000000,170.0,126.666667,760.0,149.523810

## Pivot Tables and Cross-tabulation

Pivot tables are a way to summarize data by rearranging it — think of them as a more flexible version of GroupBy that lets you spread values across both rows and columns. pd.crosstab() is a quick way to count occurrences of combinations of values.

In [969]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Sales", "HR", "Sales", "IT", "HR"],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Delhi", "Mumbai", "Pune", "Pune"],
    "Salary": [70000, 50000, 80000, 60000, 55000, 65000, 75000, 52000],
    "Gender": ["M", "F", "F", "M", "M", "F", "M", "F"]
})

df

  Department    City  Salary Gender
0         IT   Delhi   70000      M
1         HR  Mumbai   50000      F
2         IT   Delhi   80000      F
3      Sales    Pune   60000      M
4         HR   Delhi   55000      M
5      Sales  Mumbai   65000      F
6         IT    Pune   75000      M
7         HR    Pune   52000      F

In [970]:
# Pivot table → average salary by Department (rows) and City (columns)

pd.pivot_table(df, values="Salary", index="Department", columns="City", aggfunc="mean")

City          Delhi   Mumbai     Pune
Department
HR          55000.0  50000.0  52000.0
IT          75000.0      NaN  75000.0
Sales           NaN  65000.0  60000.0

In [971]:
# Pivot table with multiple aggregation functions

pd.pivot_table(df, values="Salary", index="Department", aggfunc=["mean", "count", "sum"])

                    mean  count     sum
                  Salary Salary  Salary
Department
HR          52333.333333      3  157000
IT          75000.000000      3  225000
Sales       62500.000000      2  125000

In [972]:
# pd.crosstab() → counts how many times each combination of values appears

pd.crosstab(df["Department"], df["Gender"]) # How many Male and Female employees are in each department

Gender      F  M
Department
HR          2  1
IT          1  2
Sales       1  1

In [973]:
# crosstab with normalize=True gives proportions instead of counts

pd.crosstab(df["Department"], df["Gender"], normalize='index') # Shows proportion within each department (row)

Gender             F         M
Department
HR          0.666667  0.333333
IT          0.333333  0.666667
Sales       0.500000  0.500000

## Key Takeaways

- Pandas is built on NumPy — use .values to convert a DataFrame to a NumPy array.
- loc uses label-based indexing and iloc uses position-based indexing.
- Always check isnull().sum() first when loading a new dataset to understand missing data.
- Use dropna() to remove rows/columns with missing data, fillna() to fill them, and interpolate() for time-series gaps.
- sort_values() sorts by column values, sort_index() sorts by index labels.
- Adding a column is as simple as df['new_col'] = ..., and drop() removes columns (axis=1) or rows (axis=0).
- apply() and map() are the most powerful tools for custom transformations — avoid using for loops on DataFrames.
- transform() is like apply() but keeps the result aligned with the original DataFrame — essential for adding group-level features.
- pd.merge() is the SQL-style join for combining DataFrames, pd.concat() is for stacking them.
- GroupBy follows a split-apply-combine pattern and works best paired with agg().
- The str accessor handles all string operations vectorized, with automatic NaN handling.
- Always convert date columns with pd.to_datetime() before doing any time-based operations.
- rolling(), expanding(), and ewm() are essential for smoothing and trend analysis in time-series.